### ISSUE TITLE
`fatal runtime error: stack overflow` when running a test that makes use of astroid

### ISSUE THREAD

**Issue by leynos** [brownben/xc#1]
Output:

```
%  poetry run xc
xc 🏃 (Python 3.13.0 (main, Oct  7 2024, 05:02:14) [Clang 15.0.0 (clang-1500.3.9.4)] darwin)
   Found 1 tests from 1 files in 0.00s
           [       0s] ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░      0/1
thread 'main' has overflowed its stack
fatal runtime error: stack overflow
zsh: abort      poetry run xc
```

Pyproject.toml:

```toml
[tool.poetry]
name = "empty"
version = "0.1.0"
description = ""
authors = ["Payton McIntosh <payton.mcintosh@___.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
astroid = "^3.3.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

test_empty.py:

```python
import astroid

def test_empty():
    source_code = """
    def foo(bar: str) -> int:
        return len(bar)
    """
    tree = astroid.parse(source_code)
    assert tree
```

Another example giving the same results:

```%  poetry run xc test_yarl.py
xc 🏃 (Python 3.13.0 (main, Oct  7 2024, 05:02:14) [Clang 15.0.0 (clang-1500.3.9.4)] darwin)
   Found 1 tests from 1 files in 0.00s
           [       0s] ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░      0/1
thread 'main' has overflowed its stack
fatal runtime error: stack overflow
zsh: abort      poetry run xc test_yarl.py
```

pyproject.toml:

```toml
[tool.poetry]
name = "xc-yarl"
version = "0.1.0"
description = ""
authors = ["Payton McIntosh <payton.mcintosh@___.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
yarl = "^1.18.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

test_yarl.py:

```python
from yarl import URL

def test_yarl():
    foo = URL('http://foo.com/')
    assert foo / 'bar'
```

This is on Apple Silicon / Mac OS v14.7.1 (23H222):

```
%  uname -a
Darwin EDI-MAC-PaytonM 23.6.0 Darwin Kernel Version 23.6.0: Thu Sep 12 23:36:23 PDT 2024; root:xnu-10063.141.1.701.1~1/RELEASE_ARM64_T6031 arm64
%  cargo --version
cargo 1.81.0 (2dbb1af80 2024-08-20)
```

Any other information I can provide to be of assistance?
